### ISSUE TITLE
Gestion des modes de jeu SOLO / VERSUS

### ISSUE THREAD

**Issue by julienbordas** [mbordas/cogamu#3]
Détecter les modes de jeux, et gérer les différentes fin de parties.

Si une seul équipe au début : SOLO, fin quand :
- Bomber meurt (defeat)
- time limit (defeat)
- plus aucun wall (victory)

Si plusieurs équipes : VERSUS, fin quand une seule équipe reste en vie, et aucune bomb ou flame sur le plateau de jeu.

**Comment by mbordas** [comment]
Pour simplifier je propose de remplacer "équipe" par "joueur", avec pour le moment seulement 1 ou 2 joueurs en tout. Tout ça pour simplifier la gestion des contrôleurs ;-)

**Comment by julienbordas** [comment]
done.

**Comment by julienbordas** [comment]
Ok pour moi.
